# Generated by Django 4.1.3 on 2022-11-15 12:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PGSRoomReserving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Room')),
                ('reserving_date', models.DateField(verbose_name='Reserving date')),
                ('reserving_time', models.TimeField(verbose_name='Reserving time')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Cancel reserving')),
            ],
            options={
                'verbose_name': 'Reserving',
                'verbose_name_plural': 'Reservings',
                'ordering': ['name'],
                'get_latest_by': 'reserving',
            },
        ),
        migrations.CreateModel(
            name='PGSRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Rubric')),
                ('description', models.TextField(verbose_name='Description')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=90), size=None, verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Rubric',
                'verbose_name_plural': 'Rubrics',
                'ordering': ['name'],
                'get_latest_by': 'name',
            },
        ),
    ]
