# Generated by Django 4.1.3 on 2022-11-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgsroomreserving',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Room price'),
            preserve_default=False,
        ),
    ]
