# Generated by Django 4.1.3 on 2022-11-20 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGapp', '0002_pgsroomreserving_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Employee_f_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Employee_l_name')),
                ('birth_date', models.DateField(auto_now_add=True, verbose_name='Employee_birth_date')),
                ('address', models.CharField(max_length=100, verbose_name='Employee_address')),
                ('hire_date', models.DateField(auto_now=True, verbose_name='Employee_hire_date')),
                ('phone', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Employee_phone')),
                ('photo', models.ImageField(blank=True, height_field=140, null=True, upload_to='', verbose_name='Employee_photo', width_field=140)),
            ],
        ),
    ]
