# Generated by Django 4.1.3 on 2022-11-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGapp', '0004_alter_hotelemployees_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelemployees',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static', verbose_name='Employee Photo'),
        ),
    ]
