# Generated by Django 4.1.3 on 2022-11-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGapp', '0005_alter_hotelemployees_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelemployees',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='hotelemployees',
            name='photo',
            field=models.ImageField(blank=True, default='default', null=True, upload_to='img/', verbose_name='Employee Photo'),
        ),
    ]
