# Generated by Django 4.1.3 on 2022-11-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGapp', '0006_alter_hotelemployees_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelemployees',
            name='photo',
            field=models.ImageField(blank=True, default='D:/A_PYTHONPROJECTS/Revashing/folder/PGsite/media/img/default.jpg', null=True, upload_to='img/%Y/%m/%d/', verbose_name='Employee Photo'),
        ),
    ]
