# Generated by Django 4.1.3 on 2022-11-24 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGapp', '0007_alter_hotelemployees_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelemployees',
            name='photo',
            field=models.ImageField(blank=True, default='D:/A_PYTHONPROJECTS/Revashing/folder/PGsite/media/img/default.jpg', error_messages={'invalid_extension': 'This format is not allowed'}, null=True, upload_to='img/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png'))], verbose_name='Employee Photo'),
        ),
    ]
