# Generated by Django 4.1.3 on 2022-12-02 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGapp', '0008_alter_hotelemployees_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Room Title')),
                ('picture', models.ImageField(blank=True, default='D:/A_PYTHONPROJECTS/Revashing/folder/PGsite/media/img/room_default.png', error_messages={'invalid_extension': 'This format is not allowed'}, null=True, upload_to='img/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png'))], verbose_name='Room Picture')),
                ('price', models.IntegerField(verbose_name='Room Price')),
                ('description', models.TextField(verbose_name='Room Description')),
            ],
            options={
                'verbose_name': 'Hotel Room',
                'verbose_name_plural': 'Hotel Rooms',
            },
        ),
    ]
