# Generated by Django 4.1.3 on 2022-12-03 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PGapp', '0009_hotelrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelemployees',
            name='photo',
            field=models.ImageField(blank=True, default='D:/A_PYTHONPROJECTS/Revashing/folder/PGsite/media/img/default.jpg', error_messages={'invalid_extension': 'This format is not allowed'}, null=True, upload_to='img/Employee_pics/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png'))], verbose_name='Employee Photo'),
        ),
        migrations.AlterField(
            model_name='hotelrooms',
            name='picture',
            field=models.ImageField(blank=True, default='D:/A_PYTHONPROJECTS/Revashing/folder/PGsite/media/img/room_default.png', error_messages={'invalid_extension': 'This format is not allowed'}, null=True, upload_to='img/Hotel_Room_pics/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png'))], verbose_name='Room Picture'),
        ),
    ]
