# Generated by Django 4.1.3 on 2022-12-05 17:10

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PGapp', '0011_hotelrooms_picture_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelrooms',
            name='picture_thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='D:/A_PYTHONPROJECTS/Revashing/folder/PGsite/media/img/room_thumbnail_default.png', upload_to='img/Hotel_Room_thumbnails/%Y/%m/%d/'),
        ),
    ]
